### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue#103]
Files for translation for venue-server are in [the locale directory](https://github.com/Volentix/venue-server/tree/master/locale). Since there is no replacement text, should be easy to do.

Files for translation for venue-client are in [the lang directory](https://github.com/Volentix/venue-client/tree/master/venue/lang). Documentation for this is available at [http://kazupon.github.io/vue-i18n/](vue-i18n documentation).

In both cases you can send the files to external services, and then create a pull request to submit them to these 2 repositories.

**Comment by shawnlauzon** [comment]
@Mojganahk Any update on translations?

**Comment by Mojganahk** [comment]
@shawnlauzon Not yet.

**Comment by shawnlauzon** [comment]
I'm marking this as done; translations for Turkish are now complete (except for referral bonuses, which are in progress now).
