### ISSUE TITLE
Leaderboard performance super slow

### ISSUE THREAD

**Issue by realrhys** [Volentix/venue#119]
I have (locally) added 1000 users (i will be doing this remotely later) and the call takes 18s... Even refreshes take 18s. It looks like the issue is 3 fold:
1. No caching
2. Returning every users data (rather than just the top)
3. Leaderboard quiery is way to expensive.

Although this is local, the impact will be obvious even on large servers... Truth is 1000 users in not a lot... what about when we have 10000 users?

**Comment by shawnlauzon** [comment]
I'm assigning this to @alexdashkov ... and it's a top priority.

@joemarct If you have some thoughts, you're welcome to share them.

**Comment by shawnlauzon** [comment]
@realrhys Can you see from your tooling if the time is being spent accessing the database or somewhere else?

@alexdashkov The first thing I suggest looking into is to see if the proper indexing is setup. If that doesn't solve the problem (and I suspect it won't completely), then adding a caching solution might be the best option. Interested to know your thoughts.

**Comment by realrhys** [comment]
Guys....

You can now see this in action here: https://venue-perf.volentix.io/api/retrieve/leaderboard-data/

It now takes 30s on my machine.

@alexdashkov Lets talk this out together in order for you to recreate the issue... The short of it is that I now have the 'performance-testing' branch. I would like for the changes to be on this branch if possible. Although we can discuss that later.

@shawnlauzon No pull request on this branch until we can fix this problem..
