### ISSUE TITLE
Access to pages not logged into

### ISSUE THREAD

**Issue by realrhys** [Volentix/venue#123]
You are now able to log out and see the 'dashboard' page. In the past you where not able to do that.... I think this needs fixing.

**Comment by shawnlauzon** [comment]
@Lyncis Please take a look at this, thanks.

**Comment by shawnlauzon** [comment]
I replicated it: https://venue-uat.volentix.io/dashboard should redirect to https://venue-uat.volentix.io, but it does not. The `middleware: "authenticated"` line was somehow removed from the dashboard page.
