### ISSUE TITLE
The referral URL should use the current server

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue#127]
**Describe the bug**
The referral URL is always https://venue.volentix.io even when running on a different server

**To Reproduce**
1. Go to 'https://venue-dev.volentix.io'
2. Sign in
3. Click on Invite a friend
4. See the URL

**Expected behavior**
In this case, URL should be https://venue-dev.volentix.io/signup ...

**Screenshots**
![image](https://user-images.githubusercontent.com/611529/44108991-eda56e0a-9fc9-11e8-84e5-40fbe036a10c.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**
n/a

**Comment by Lyncis** [comment]
@shawnlauzon 
Help is needed - how can I retrieve the base link for the current server? (e.g. venue.volentix.io or venue-dev.volentix.io').
I tried different approaches and I can't get it and therefore create the link correctly.

**Comment by shawnlauzon** [comment]
`location.hostname`: see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Location)

P.S. I didn't know the answer, I just did some googling: a developer's best friend!
