### ISSUE TITLE
Signup email is incorrect for referral emails

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue#132]
**Describe the bug**
The referral email that I sent to myself looks like the signup confirmation email. It should be the referral email.

**To Reproduce**
1. Sign into Venue
2. Click on 'Invite a friend'
3. Enter an email address and click send
4. Open email
5. See the incorrect email

**Expected behavior**
I should see the email which is appropriate for a brand new user who doesn't know much about Venue.

**Screenshots**
![image](https://user-images.githubusercontent.com/611529/44111850-8c64d664-9fd1-11e8-8fe2-fcd123791aa2.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**
I hit this on localhost because the server Postmark API Key isn't currently setup. It should be able to be reproduced anywhere.

**Comment by alexdashkov** [comment]
@shawnlauzon could you please update your local version and rebuild an image? It seems that you have an old codebase.

**Comment by shawnlauzon** [comment]
Dev is now running and it works well, so must be a problem with my installation. Thanks.
