### ISSUE TITLE
Referral bonus should be 100 VTX

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue#135]
**Describe the bug**
The referral bonus is stated as 10 VTX; it should be 100

**To Reproduce**
1. Log into Venue
2. Click on Invite a friend
3. See the bonus is 10 VTX

**Expected behavior**
Should be 100 VTX

**Screenshots**
![image](https://user-images.githubusercontent.com/611529/44117087-486a826a-9fe0-11e8-969a-bffeaff9bcd5.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**
This is a variable which is configurable on the server. So it should be returned as part of one of the API calls and then consumed by the client code. I think the best place for that is `/api/retrieve/site-configs`. I don't think the client code calls that function yet; it should probably be done in `store/index.js/nuxtServerInit`

**Comment by Lyncis** [comment]
Fixed
