### ISSUE TITLE
Referred users who have joined campaign are not displayed

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue#136]
**Describe the bug**
Even after going through the join a campaign flow, the user sending a referral is not earning VTX.

**To Reproduce**
1. Sign into Venue and click on Invite a Friend
2. Enter new email address
3. Check email address and copy & paste link into 2nd browser
4. Create new user & verify email in 2nd browser
5. Go through Join a Campaign flow and successfully register Bitcointalk User
6. Go to leaderboard and see my new user
7. Go back to 1st browser and click on Invite a Friend
8. See that my VTX is still 0. Refreshing the browser and logging out and logging in have no effect.

**Expected behavior**
When I refresh the 1st browser, I should see the users who I referred, as well as earning VTX

**Screenshots**
After the signup flow:
![image](https://user-images.githubusercontent.com/611529/44120465-6d874ef2-9fea-11e8-974f-8d007a6c0103.png)

However, if I reload the page, I see a flash of the table without a username and the status of "Pending".

However, if I stop before joining a campaign, the user is correctly displayed:
![image](https://user-images.githubusercontent.com/611529/44120437-5d6ca7ce-9fea-11e8-841f-aba7db8ea78d.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Additional context**

**Comment by Lyncis** [comment]
@shawnlauzon 
Any way I can test this without being a bitcointalk user? Can't reproduce this completely without joining the campaign.

**Comment by shawnlauzon** [comment]
It's easy to create a user on bitcointalk, so you should just do that. And
all user levels are ok on dev, or on localhost if you go into /admin
(admin/default2018) and enable Test mode in the config section.

**Comment by shawnlauzon** [comment]
So the server side code is correct. Do you see any possible way that the client could get confused? Because I don't see anything that I did wrong in testing. Perhaps some sort of race condition, or that there is something being loaded which might not be set all the time? The flashing behaviour that I mentioned might give a hint.

**Comment by Lyncis** [comment]
I'll investigate this.
For now, I don't see why it can get confused, but I'll try to locate the problem

**Comment by shawnlauzon** [comment]
Ok; if you don't see anything after 20 minutes or so, let me know and I'll look. Thanks!

**Comment by Lyncis** [comment]
@shawnlauzon 
ok, I followed your actions step by step and I couldn't reproduce the problem. Without it, it is difficult to understand what can be wrong and why it is acting this way. I tried to figure out what in the code can cause the problem, but couldn't see anything.

**Comment by shawnlauzon** [comment]
This is still failing for me on UAT. I will continue to debug on localhost

**Comment by shawnlauzon** [comment]
Now I'm not able to reproduce on Dev. Closing for now; perhaps some other code change resolved it.
