### ISSUE TITLE
Review BB code signatures to see where all links point.

### ISSUE THREAD

**Issue by volentixnonton11** [Volentix/venue#142]
The purpose of this issue is to verify what links are in a signature and where those links are pointing. 

Could a document be created with image of each signature and specifying where each to the links should point. Could this be assigned to Jimbo @shawnlauzon ?

**Comment by shawnlauzon** [comment]
You can find the BBCode (which is where the links are stored) for UAT at https://venue-uat.volentix.io/admin/venue/signature/ -- this should be the same as that in Production.
