### ISSUE TITLE
Inform users to check their spam folder upon sign-up

### ISSUE THREAD

**Issue by Jimb0vlabs** [Volentix/venue#145]
The sign up verification email moves to the spam folder, if we could add a little text on the sign up page saying "please check your emails spam folder"

**Comment by shawnlauzon** [comment]
That's really surprising; I've never seen it hit my spam folder. But it's easy enough to add that text. 

@Lyncis please add text to the message which pops up saying to check your email. There should be a new paragraph: "In rare cases the verification email may be marked as spam. If you have not received an email, please check your spam folder to see if it is there. Thank you."

**Comment by Lyncis** [comment]
I just added the text:

![screen shot 2018-08-23 at 11 21 34 am](https://user-images.githubusercontent.com/8875863/44536019-81231f00-a6c9-11e8-8a13-72f6a3001380.png)
