### ISSUE TITLE
Sufficient logging to diagnose problems

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue#146]
There doesn't seem to be enough logging to actually understand what is going on. We should ensure that we at least have figured out the logging solution before turning on prod.

@joemar has suggested LogDNA:

> I have tried using LogDNA before -- a cloud-based log aggregation service.
> https://docs.logdna.com/docs
> It might be the quickest to setup to monitor detailed logs when needed.
> What's really helpful is their logging agent program. Just tell it where your logfiles > are and it's good to go. No additional coding required.
> 
> https://docs.logdna.com/docs/logdna-agent

**Comment by joemarct** [comment]
I suggest we use LogDNA -- a cloud-based log aggregation service. Docs: https://docs.logdna.com/docs

It might be the quickest to setup to monitor detailed logs when needed.

What's really helpful is their logging agent program. Just tell it where your logfiles are and it's good to go. No additional coding required. See here: https://docs.logdna.com/docs/logdna-agent

**Comment by realrhys** [comment]
Potential candidate.
https://github.com/logdna/logdna-agent#kubernetes-logging
