### ISSUE TITLE
Venue & Verto-specific Terms and Conditions

### ISSUE THREAD

**Issue by realrhys** [Volentix/venue#152]
https://docs.google.com/document/d/14r0x1ZG77uVeY35JjX8aMp-X9QnJT_SouXKH5ycl1KY/edit

Points to Terms and Conditions on volentix.io

**Comment by shawnlauzon** [comment]
@realrhys The T&Cs on Venue already point to the T&Cs on volentix.io. Is there anything else which needs to be done?

**Comment by realrhys** [comment]
Not my call but I think that would be ok... perhaps check in with Nemr.

**Comment by shawnlauzon** [comment]
from Nemr:

> This is only VERTO and VENUE.
Please make sure that big Verto and venue also display a clear disclaimer for NO US PERSONS on signup, this is very important.
Thank you 
NH
