### ISSUE TITLE
Email signup

### ISSUE THREAD

**Issue by volentixnonton11** [Volentix/venue#154]
Everyone on Venue subscribes to email marketing this is not be optional

**Comment by volentixnonton11** [comment]
![Screen Shot 2018-09-04 at 3.50.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b608fe6a21db80013d255d2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f76b7191a37bf1172b4f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ebc87680b20923a44f8bed71bbe01ba21df1ed3beb48c44d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54de14455ac153460ee762431.png)

**Comment by shawnlauzon** [comment]
@papotus What should be done with the users who did not check the box? If we just add them to the newsletter, I think we would be disregarding their wishes, which I don't think is legal.

Also, do we need to include something in the privacy policy or terms of use to tell people that they agree to the newsletter? And if this is something that was just added, do we need to send an email to users telling them that some policy has changed?

I just want to make sure we don't do anything that would get us in trouble legally.

**Comment by shawnlauzon** [comment]
Ok, I have removed the checkbox and added text which states that you will be added to the Volentix by signing up. I have kept it as a field in the database, and so people who did not check the box will still be noted on the list of email addresses.

![Screen Shot 2018-09-10 at 5.26.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6a5bdfb6d90e001285d14c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455f36b7191a37df1102d4f5f5d5ecc3c4a4356bcbbd671f3e57862804e0ebfd96b0e7c956c45aebc801cba01ba228e1b81b4e9df1fd2f42f67b6d5db1063474f4dcbed5727a19141c95df54de74c51ac113062e6712431.png)
