### ISSUE TITLE
Emails to database maintained by Mojgan

### ISSUE THREAD

**Issue by volentixnonton11** [Volentix/venue#184]
The emails need to be sent to the same database that Mojgan is managing because they need to be fed newsletters and other updates about the wallet etc.

**Comment by shawnlauzon** [comment]
I assume we need to push emails whenever a user signs up. This means need to support:

- [ ] Push email when user signs up
- [ ] Change email when user changes email

I've asked @Mojganahk for access to Constant Contact so I can create an API key.

**Comment by Mojganahk** [comment]
" Venue webapp " is the name of email list. created on oct25. @shawnlauzon

**Comment by volentixnonton11** [comment]
Hey, just to let you know, we asked Joemar for help with this and after about 30mins he was able to figure it out. I think we just need to review it and then close the issue ;-)
