### ISSUE TITLE
Telegram Campaign Spam

### ISSUE THREAD

**Issue by volentixnonton11** [Volentix/venue#185]
Telegram Campaign has been spammed with 6300 submissions. 

a. confirm there has not been 6300 recent venue signups within 2 weeks
b. provide a list of all signups since oct ? confirm date of campaign change
c. create a system for providing recent signups on venue to Bounty manager so that spreadsheets can be cross referenced for superfluous submissions
d. create a means to automate this flow, possibly take out google sheet part of submission and replace with venue flow and captcha

**Comment by shawnlauzon** [comment]
1. There are currently 369 users signed up for Venue:
![image](https://user-images.githubusercontent.com/611529/47583096-63ba3d80-d924-11e8-9f00-e465eee052de.png)
2. I will be providing a list of all signups to @Mojganahk after #184 is complete. I see nothing that looks suspicious (5-10 users created most days).
3. As part of #184, each new user will be added to Constant Contact. I suggest that the Bounty manager use Constant Contact as the single place where user information is maintained (@Mojganahk can you confirm that this is a good idea?)
4. I created #186 to track integration of captcha into Venue.

@volentixnonton11 Is that sufficient?

**Comment by volentixnonton11** [comment]
I will schedule a review to go over questions related to this but I believe this is a good solution. 
1. Very cool!
2. great thanks! Will the list be time stamped so we see the date joined ? To solve the spam received, we will want t have a list created for a specific date range in 
3. Need to review this...."each new user will be added to Constant Contact" what does that mean ?  Is this following constant contacts double opt-in or this is just forwarding the databases to be merged ? 
4. Thanks that sounds great, let's discuss in a call asap

**Comment by shawnlauzon** [comment]
> great thanks! Will the list be time stamped so we see the date joined ? To solve the spam received, we will want t have a list created for a specific date range in
Each entry is time stamped, yes

> Need to review this...."each new user will be added to Constant Contact" what does that mean ? Is this following constant contacts double opt-in or this is just forwarding the databases to be merged ?
When a user confirms their email, they will be automatically added to the Constant Contact list called "Venue Webapp" via the Constant Contact API (I discussed this with @Mojganahk, and she told me that because we do not have a single list for the newsletter, having a list for Venue is best). 
There is no need for the user to confirm being added to the list, because they have already confirmed their email with Venue.
